version: "3.7"

# Application Containers
services:
  # Plugin Container
  apromore-preprocessing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - maven-cache:/m2

volumes:
  maven-cache:
