version: "3.7"

services:
  apromore-preprocessing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - maven_cache:/m2
    ports:
      - "8080:8080"
  
  impala:
    ports:
      - "21050:21050"

volumes:
  maven_cache:
