version: "3.7"

# Application Containers
services:
  # Plugin Container
  apromore-preprocessing:
    image: omjadas/swen90013-bp:latest
    environment:
      - IMPALA_LINK=jdbc:impala://impala:21050
      - DATA_STORE=/preprocess_data
    depends_on:
      - impala
    volumes:
      - preprocess-data:/tmp/preprocess_data

  # Apache Impala Container
  impala:
    image: apache/kudu:impala-latest
    volumes:
      - preprocess-data:/tmp/preprocess_data
    command: impala

# Volume to store Log files
volumes:
  preprocess-data:
