@startuml classes

namespace org {
    namespace apromore {
        namespace service {
            namespace FileImporterLogic {
                namespace impl {
                    class FileImporterLogicImpl
                    class TransactionImpl

                    class Select {
                        - String column
                        - String as
                        + Select(String column)
                        + Select(String column, String as)
                    }

                    class Concatenate {
                        - String[] columns
                        - String delimiter
                        - String newColumnName
                        + Concatenate(String[] columns, String delimiter, String newColumnName)
                    }

                    class If {
                        - String condition
                        - String true
                        - String false
                        + If(String condition, String true, String false)
                    }

                    class Join {
                        - String file
                        - String joinKey1
                        - String joinKey2
                        + Join(JoinType joinType, String file, String joinKey1, String joinKey2)
                    }

                    FileImporterLogicImpl ..|> org.apromore.service.FileImporterLogic.FileImporterLogic
                    TransactionImpl ..|> org.apromore.service.FileImporterLogic.Transaction

                    Select ..|> org.apromore.service.FileImporterLogic.Statement
                    Concatenate ..|> org.apromore.service.FileImporterLogic.Statement
                    If ..|> org.apromore.service.FileImporterLogic.Statement
                    Join ..|> org.apromore.service.FileImporterLogic.Statement
                    Join --* "1" org.apromore.service.FileImporterLogic.JoinType : - joinType
                }

                interface Statement {
                    + String toString()
                }

                enum JoinType {
                    LEFT
                    INNER
                    RIGHT
                    FULL_OUTER
                }

                interface Transaction {
                    - String file
                    - String[] selectedColumns
                    + Transaction(String file)
                    + Transaction join(JoinType joinType, String file)
                    + Transaction select(String column)
                    + Transaction select(String column, String as)
                    + Transaction order(String[] columns)
                    + Transaction if(String condition, String true, String false)
                    + Transaction concatenate(String[] columns, String delimiter, String newColumnName)
                    + Transaction where(String column, Comparison comparison, String value)
                    + ResultSet execute()
                }

                interface FileImporterLogic {
                    + String[][] getSnippet(Transaction transaction, int rows)
                    + void exportFiles(Transaction transaction)
                }

                Transaction --* "*" "Statement" : + statements
            }
        }

        namespace plugin {
            namespace portal {
                namespace FileImporterPortal {
                    namespace impl {
                        class FileUploadServiceImpl
                        class FileExporterServiceImpl

                        FileUploadServiceImpl ..|> org.apromore.plugin.portal.FileImporterPortal.FileUploadService
                        FileExporterServiceImpl ..|> org.apromore.plugin.portal.FileImporterPortal.FileExporterService
                        FileExporterServiceImpl --* "1" org.apromore.service.FileImporterLogic.FileImporterLogic : - fileImporterLogic
                    }

                    class FileUploadViewModel {
                        + void init()
                        + void onFileUpload()
                    }

                    interface FileUploadService {
                        + void writeFiles(Media[] media)
                    }

                    class FileExporterViewModel {
                        + void init()
                        + void onFileImport()
                    }

                    interface FileExporterService {
                        + void getSnippet(Operation[] operations)
                        + void importFiles(Media[] media, Operation[] operations)
                    }

                    FileUploadViewModel --* "1" FileUploadService : - fileUploadService
                    FileExporterViewModel --* "1" FileExporterService : - fileExporterService
                }
            }
        }
    }
}

@enduml
