name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: master
      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Pull Docker images
        run: docker pull -a omjadas/swen90013-bp
      - name: Build and push Docker image (caddy)
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: omjadas/swen90013-bp
          dockerfile: Dockerfile.caddy
          tags: caddy
          cache_froms: omjadas/swen90013-bp:caddy
      - name: Build and push Docker image (build)
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: omjadas/swen90013-bp
          tags: build
          target: build
          cache_froms: omjadas/swen90013-bp:build
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: omjadas/swen90013-bp
          tags: latest
          cache_froms: omjadas/swen90013-bp:build,omjadas/swen90013-bp:latest
      - name: Deploy
        run: |
          DOCKER_HOST="${{ secrets.DOCKER_HOST }}" \
            BASIC_AUTH_USERNAME="${{ secrets.BASIC_AUTH_USERNAME }}" \
            BASIC_AUTH_PASSWORD_HASH="${{ secrets.BASIC_AUTH_PASSWORD_HASH }}" \
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
      - name: Update deployment status
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
