name: Deploy to Dokku

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: master
      - name: Deploy to Dokku
        uses: vitalyliber/dokku-github-action@v4.0
        env:
          PRIVATE_KEY: ${{ secrets.DOKKU_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.DOKKU_PUBLIC_KEY }}
          HOST: ${{ secrets.DOKKU_HOST }}
          PROJECT: ${{ secrets.DOKKU_PROJECT }}
          FORCE_DEPLOY: "true"
      - name: Update deployment status
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
